### ISSUE TITLE
Requirements.txt not in sdist

### ISSUE THREAD

**Issue by chrisjbillington** [kajchang/runkeeper#1]
In the .tar.gz downloaded from PyPI with pip, the file requirements.txt is not present, leading to an exception when running `pip install runkeeper`.

You might consider adding `setup_requires=['setuptools, ''setuptools_scm']` to `setup()` to automatically include everything under version control, or adding manually to a `MANIFEST.in`

**Comment by kaijchang** [comment]
Sorry, should work now.

Thanks for the tip!

**Comment by chrisjbillington** [comment]
Thanks for the quick fix, installing from pip works now :)
